#ifndef CONSTANTES_H
#define CONSTANTES_H

//#define MODO_PORTATIL 1

#define MARGENES_VISOR_ALTURAS 30

#define DIAMETRO_MARCA_WAYPOINT 20
#define DIAMETRO_MARCA_WAYPOINT_PORTATIL 30

#define RADIO_MARCA_WAYPOINT 10
#define RADIO_MARCA_WAYPOINT_PORTATIL 15
#define DIAMETRO_WP_CIRCULO 100
#define ALTURA_DEFECTO 70


#define RUTA_FICHERO_CAMARAS "./camaras.cam"
#define RUTA_FICHERO_AVIONES "./aviones.cfg"
#define ENCRIPTION_KEY 0x0c2ad4a4acb9f023

#define CAM_POSICION_MARCA 0
#define CAM_POSICION_MODELO 1
#define CAM_POSICION_NOTAS 2
#define CAM_POSICION_WIDTH_PIXEL 3
#define CAM_POSICION_HEIGHT_PIXEL 4
#define CAM_POSICION_WIDTH_MM 5
#define CAM_POSICION_HEIGHT_MM 6
#define CAM_POSICION_LENS_FOCAL_LENGTH_MM 7
#define CAM_POSICION_PLATFORM_GROUND_SPEED 8
#define CAM_POSICION_FLIGHT_HEIGHT_METERS 9
#define CAM_POSICION_FORWARD_OVERLAP 10
#define CAM_POSICION_SIDE_OVERLAP 11
#define CAM_POSICION_AOI_WIDTH_METERS 12
#define CAM_POSICION_AOI_LENGTH_METERS 13

#define AVION_POSICION_EMPRESA 0
#define AVION_POSICION_MODELO 1
#define AVION_POSICION_VERSION 2
#define AVION_POSICION_RUTAIMAGEN 3
#define AVION_POSICION_PITCH_MAXIMO 4
#define AVION_POSICION_PITCH_MINIMO 5
#define AVION_POSICION_VELOCIDAD_CRUCERO 6
#define AVION_POSICION_BASE_CIRCUIT 7
#define AVION_POSICION_RECORRIDO_CIRCUIT 8
#define AVION_POSICION_HEADER 9
#define AVION_POSICION_FOOTER 10

#define CONFIG_POSICION_IDIOMA 0
#define CONFIG_POSICION_RUTA_HORIZON 1




#endif // CONSTANTES_H

